# Generated by Django 5.0.7 on 2024-08-21 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogauthor',
            name='bio',
            field=models.TextField(default='Bio', max_length=200),
        ),
        migrations.AlterField(
            model_name='blogdetailcategoriesplacement',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to='blogpage.blogcategories'),
        ),
    ]
