# Generated by Django 5.0.7 on 2024-08-06 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpage', '0002_blogdetail_cta_url_four_blogdetail_cta_url_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetail',
            name='cta_url_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blogpage.blogdetail'),
        ),
    ]
