# Generated by Django 5.0.7 on 2024-08-06 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpage', '0003_alter_blogdetail_cta_url_one'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetail',
            name='cta_url_four',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blogpage.blogdetail'),
        ),
        migrations.AlterField(
            model_name='blogdetail',
            name='cta_url_three',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blogpage.blogdetail'),
        ),
        migrations.AlterField(
            model_name='blogdetail',
            name='cta_url_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blogpage.blogdetail'),
        ),
    ]
