# Generated by Django 5.0.7 on 2024-08-07 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpage', '0006_blogauthor'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetail',
            name='blog_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blogpage.blogauthor'),
        ),
    ]
