# Generated by Django 5.0.7 on 2024-08-07 13:36

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpage', '0007_blogdetail_blog_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogDetailAuthorPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blogpage.blogauthor')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_placement', to='blogpage.blogdetail')),
            ],
        ),
    ]
