# Generated by Django 5.0.7 on 2024-08-07 15:58

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpage', '0010_remove_blogdetail_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetail',
            name='body',
            field=wagtail.fields.StreamField([('text', 0), ('image', 1)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {})}, null=True),
        ),
    ]
