# Generated by Django 5.0.7 on 2024-08-09 16:01

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpage', '0016_alter_blogdetail_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='blogdetail',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', 0), ('text', 1), ('document', 2), ('page', 3), ('author', 4), ('info', 5), ('faq', 6), ('carousel', 10), ('image', 11), ('embed', 12), ('code', 15), ('blockquote', 16), ('quotation', 18), ('call_to_action_1', 22)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('blocks.blocks.TextBlock', (), {}), 2: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 3: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 4: ('wagtail.snippets.blocks.SnippetChooserBlock', ('blogpage.Author',), {}), 5: ('blocks.blocks.InfoBlock', (), {}), 6: ('blocks.blocks.FAQListBlock', (), {}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 8: ('wagtail.blocks.TextBlock', (), {}), 9: ('wagtail.blocks.StructBlock', [[('text', 8), ('author', 8)]], {}), 10: ('wagtail.blocks.StreamBlock', [[('image', 7), ('quotation', 9)]], {}), 11: ('blocks.blocks.ImageBlock', (), {}), 12: ('wagtail.embeds.blocks.EmbedBlock', (), {}), 13: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('bash', 'Bash/Shell'), ('css', 'CSS'), ('diff', 'diff'), ('html', 'HTML'), ('javascript', 'Javascript'), ('json', 'JSON'), ('python', 'Python'), ('scss', 'SCSS'), ('yaml', 'YAML')], 'help_text': 'Coding language', 'identifier': 'language', 'label': 'Language'}), 14: ('wagtail.blocks.TextBlock', (), {'identifier': 'code', 'label': 'Code'}), 15: ('wagtail.blocks.StructBlock', [[('language', 13), ('code', 14)]], {}), 16: ('wagtail.blocks.BlockQuoteBlock', (), {}), 17: ('wagtail.blocks.TextBlock', (), {'required': False}), 18: ('wagtail.blocks.StructBlock', [[('quote', 0), ('cite', 17)]], {'icon': 'openquote', 'template': 'blocks/blockquote.html'}), 19: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'required': True}), 20: ('wagtail.blocks.PageChooserBlock', (), {}), 21: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': False}), 22: ('wagtail.blocks.StructBlock', [[('text', 19), ('page', 20), ('button_text', 21)]], {})}, null=True),
        ),
    ]
