# Generated by Django 5.0.7 on 2024-08-11 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpage', '0018_blogcategories_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogdetailcategoriesplacement',
            old_name='categories',
            new_name='category',
        ),
    ]
