# Generated by Django 5.0.7 on 2024-08-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpage', '0019_rename_categories_blogdetailcategoriesplacement_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogauthor',
            name='bio',
            field=models.TextField(default='Bio', max_length=300),
        ),
    ]
