# Generated by Django 5.0.7 on 2024-08-11 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpage', '0021_blogauthorpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogauthorpage',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page', to='blogpage.blogauthor'),
        ),
    ]
