# Generated by Django 5.0.7 on 2024-08-12 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpage', '0023_alter_blogauthorpage_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageUser',
        ),
    ]
