# Generated by Django 5.0.7 on 2024-08-12 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpage', '0024_delete_messageuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogauthor',
            name='behance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogauthor',
            name='dribbble',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogauthor',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogauthor',
            name='github',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogauthor',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogauthor',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogauthor',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogauthor',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogauthor',
            name='x',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
