# Generated by Django 5.0.7 on 2024-08-12 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpage', '0025_blogauthor_behance_blogauthor_dribbble_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogAuthorPage',
        ),
    ]
