# Generated by Django 5.0.7 on 2024-08-12 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpage', '0026_delete_blogauthorpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategories',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blogcategories',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
