# Generated by Django 5.0.7 on 2024-08-12 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpage', '0027_blogcategories_url_alter_blogcategories_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpagetag',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
