# Generated by Django 5.0.7 on 2024-08-12 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpage', '0028_blogpagetag_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
