# Generated by Django 5.0.7 on 2024-08-23 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericFooterInfoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_info', models.TextField(blank=True, help_text='Text to display in the footer of the site.', null=True)),
                ('copyright_text', models.CharField(blank=True, help_text='Copyright text to display in the footer of the site.', max_length=255, null=True)),
                ('copyright_link_text', models.CharField(blank=True, help_text='Text for the copyright link.', max_length=255, null=True)),
                ('copyright_link', models.URLField(blank=True, help_text='Link for the copyright text.', null=True)),
                ('main_link_title', models.CharField(blank=True, help_text='Title for the main link.', max_length=255, null=True)),
                ('site_settings_link_title', models.CharField(blank=True, help_text='Title for the site settings link.', max_length=255, null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenericFooterLogoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_logo', models.ForeignKey(blank=True, help_text='Logo to display in the footer of the site.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialMediaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, help_text='Facebook URL', null=True)),
                ('x', models.URLField(blank=True, help_text='X URL', null=True)),
                ('linkedin', models.URLField(blank=True, help_text='LinkedIn URL', null=True)),
                ('xing', models.URLField(blank=True, help_text='Xing URL', null=True)),
                ('instagram', models.URLField(blank=True, help_text='Instagram URL', null=True)),
                ('github', models.URLField(blank=True, help_text='GitHub URL', null=True)),
                ('behance', models.URLField(blank=True, help_text='Behance URL', null=True)),
                ('dribbble', models.URLField(blank=True, help_text='Dribbble URL', null=True)),
                ('figma', models.URLField(blank=True, help_text='Figma URL', null=True)),
                ('unsplash', models.URLField(blank=True, help_text='Unsplash URL', null=True)),
                ('youtube', models.URLField(blank=True, help_text='YouTube URL', null=True)),
                ('tiktok', models.URLField(blank=True, help_text='TikTok URL', null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
