# Generated by Django 5.0.7 on 2024-08-17 13:36

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standardpage', '0002_alter_standardpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardpage',
            name='image',
            field=wagtail.fields.StreamField([('image', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {})}, null=True),
        ),
    ]
